[flotilla]
key="key"
entries = 1024
bits_per_entry = 8

[[flotilla.worker_refs]]
node_id = 0
address = "127.0.0.1:5000"
shard_start = 0
shard_stop = 10

[[flotilla.worker_refs]]
node_id = 1
address = "127.0.0.1:5001"
shard_start = 10
shard_stop = 20

[[flotilla.worker_refs]]
node_id = 2
address = "127.0.0.1:5002"
shard_start = 20
shard_stop = 32
